.\" This man page was written by Markus Koschany in May 2013 with the help of help2man.
.TH BLOBOATS "6" "May 2013" "Bloboats version 1.0.2" "User Commands"
.SH NAME
Bloboats \- a boat racing game

.SH DESCRIPTION
Bloboats is a boat game in the spirit of Elasto Mania or X-Moto,
introducing a handful of elements from Super Mario Bros \-like games.

.SH "OPTIONS"
.SS "Possible flags:"
.HP
\fB\-\-nosound\fR disables sounds
.HP
\fB\-\-sound\fR enables sounds
.HP
\fB\-\-windowed\fR or \fB\-w\fR enables windowed mode
.HP
\fB\-\-fullscreen\fR or \fB\-f\fR enables fullscreen mode
.HP
\fB\-\-resolution\fR=\fINxM\fR changes resolution to NxM
.HP
\fB\-\-nolimit\fR disables some speed limitations
.HP
\fB\-\-help\fR prints this help
